### ISSUE TITLE
Why OSX Apple Silicon is not yet supported ?

### ISSUE THREAD

**Issue by mohan-win** [foundationdb-rs/foundationdb-rs#135]
Hi,

Thanks a lot for creating a useful library. As per README.md, the OSX M1 silicon is having only tier 3 support. However, I can see that the "hello world" sample provided in [crates.io ](https://crates.io/crates/foundationdb) is working when I ran it locally on my M1 mac with latest foundation db running locally. 

Wondering if I will run into any problems using "foundationdb-rs" crate when running locally or when running in ARM based VM ? Kindly let me know.

**Comment by PierreZ** [comment]
Hi 👋 
This is a fair question. Tier 3 mostly means that ARM build "should" works, but there is no CI to prove it. Also, please note that Apple is not releasing official binaries in ARM64 because their extensive CI using simulation has not ARM setup. From my understanding, only simple tests are runned, not the whole "run millions of simulation to search for faulty seeds on thousands of machines".

To answer your question, I'm glad to see it working. However, you may run into [issues like this one](https://forums.foundationdb.org/t/unable-to-get-it-running-locally-on-macos/4466/2) and others.

**Comment by mohan-win** [comment]
Got it. Thank you.

**Comment by danthegoodman1** [comment]
@PierreZ are these not considered official releases for arm? https://github.com/apple/foundationdb/releases/tag/7.1.60

It seems more recently people are having out of the box success with both the server and client on apple silicon

**Comment by danthegoodman1** [comment]
Does the [FoundationDB-7.1.60_arm64.pkg](https://github.com/apple/foundationdb/releases/download/7.1.60/FoundationDB-7.1.60_arm64.pkg) not count as an official binary?

Looking to set this up myself on apple silicon for local dev.

**Comment by PierreZ** [comment]
This is fairly new, as you can see [here](https://forums.foundationdb.org/t/arm64-aarch64-binaries-available-for-the-7-3-46-releases/4512). As I expect more and more people developing using apple silicon hardware, we could add back CI on ARM
