### ISSUE TITLE
implement `Clone` on `Database`

### ISSUE THREAD

**Issue by BastienVigneron** [foundationdb-rs/foundationdb-rs#200]
In order to use fdb in a `State` in Axium, we need `Database` struct implement `Clone`.
It should be possible because the inner (`fdb_sys::FDBDatabase`) is just a type to `struct FDB_database` which implement themself `Clone`.

Open to make a PR, but I got an error with `build.rs` files:
```rust
error[E0282]: type annotations needed
  --> foundationdb-sys/build.rs:56:9
   |
56 |     let api_version;
   |         ^^^^^^^^^^^
```

**Comment by alexandrebrg** [comment]
Hello :wave: 

For this kind of usage, I believe you shouldn't clone the whole state of the database but rather use a shared pointer using `Arc<>`. Additionally, for your `api_version` error, that might be because you didn't specify a feature version of your FoundationDB client target (see `foundationdb-sys/build.rs#13). You can use `embedded-fdb-include` to use the version installed on your system.

**Comment by BastienVigneron** [comment]
Thank you @alexandrebrg , 

Yes, using an `Arc` solves the problem, but since `Database` corresponds to a binding on the native client anyway, I don't think implementing `Clone` would make much difference.
Thanks for the tip on `api_version`, I found the solution after posting my question, so a little README update would be good.
